# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-14 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('scan_account', 'Can scan 用户管理'),),
            },
        ),
    ]
