# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-14 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('scan_account', 'Can scan 用户管理'), ('scan_user', 'Can scan 用户'), ('scan_group', 'Can scan 用户组'))},
        ),
    ]
