# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-25 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('ipaddress', models.CharField(max_length=255, unique=True, verbose_name='IP地址')),
                ('hosttype', models.CharField(max_length=255, null=True, verbose_name='服务器类型')),
                ('cpu_nums', models.IntegerField(null=True, verbose_name='CPU核数')),
                ('memory', models.IntegerField(null=True, verbose_name='内存')),
                ('disk', models.IntegerField(null=True, verbose_name='磁盘')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='作业名称')),
                ('desc', models.CharField(max_length=255, verbose_name='作业描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='作业创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='作业修改时间')),
                ('content', models.TextField(max_length=255, verbose_name='作业内容')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(unique=True, verbose_name='节点ID')),
                ('node_pid', models.IntegerField(verbose_name='节点父ID')),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('level', models.IntegerField(verbose_name='层级')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='产品名称')),
                ('desc', models.CharField(max_length=255, verbose_name='产品描述')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='项目')),
                ('desc', models.CharField(max_length=255, verbose_name='项目描述')),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Product')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='服务')),
                ('desc', models.CharField(max_length=255, verbose_name='服务描述')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='service',
            field=models.ManyToManyField(db_constraint=False, null=True, to='cmdb.Node'),
        ),
    ]
