# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-25 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='service',
            new_name='node',
        ),
    ]
