# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-29 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20190325_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='product',
        ),
        migrations.RemoveField(
            model_name='service',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'permissions': (('scan_host', 'Can scan 主机'),), 'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('scan_job', 'Can scan 作业'),), 'verbose_name': '作业', 'verbose_name_plural': '作业'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'permissions': (('scan_node', 'Can scan 节点'),), 'verbose_name': '节点', 'verbose_name_plural': '节点'},
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
