# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-14 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20190329_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
