# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('scan_cmdb', 'Can scan 资源管理'),),
            },
        ),
    ]
