# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-02 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='服务名称')),
                ('desc', models.CharField(max_length=255, verbose_name='服务描述')),
                ('port', models.IntegerField(verbose_name='服务端口')),
                ('product', models.CharField(max_length=255, verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
            },
        ),
    ]
