# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-03 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='服务状态'),
        ),
    ]
