# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-03 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_service_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='服务数量'),
        ),
    ]
