# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-03 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_service_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='num',
        ),
        migrations.RemoveField(
            model_name='service',
            name='state',
        ),
    ]
