# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190403_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='log_dir',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='日志路径'),
        ),
    ]
