# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-14 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_service_log_dir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': (('scan_service', 'Can scan 服务'), ('download_log', 'Can download 服务日志')), 'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
    ]
