# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-05-14 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': (('scan_job', 'Can scan 作业'), ('exec_job', 'Can exec 作业')), 'verbose_name': '作业', 'verbose_name_plural': '作业'},
        ),
        migrations.AlterModelOptions(
            name='jobresult',
            options={'permissions': (('scan_jobresult', 'Can scan 作业结果'),), 'verbose_name': '作业结果', 'verbose_name_plural': '作业结果'},
        ),
        migrations.AlterModelOptions(
            name='jobstate',
            options={'permissions': (('scan_jobstate', 'Can scan 作业执行状态'),), 'verbose_name': '作业执行状态', 'verbose_name_plural': '作业执行状态'},
        ),
    ]
